plugins:
  yulib_integration_enabled:
    default: true
    client: true
  yulib_backend_url:
    default: "http://host.docker.internal:8080"
    client: false
  yulib_cover_books_s3_host:
    default: "https://s3.timeweb.cloud/13109edd-5c7f9725-5507-4e66-8f9a-c54f7bf66003/books/"
    client: true
  yulib_small_cover_books_s3_host:
    default: "https://s3.timeweb.cloud/13109edd-5c7f9725-5507-4e66-8f9a-c54f7bf66003/small/books/"
    client: true
  yulib_sync_interval:
    default: "24h"
    client: false
  yulib_use_small_covers:
    default: true
    client: false
  yulib_max_books_per_status:
    default: 30
    client: true
  # START Настройки пушей (FCM)
  yulib_fcm_enabled:
    default: false
    client: true
  yulib_fcm_project_id:
    default: ''
  yulib_fcm_api_key:
    default: ''
  yulib_fcm_google_json:
    default: ''
    textarea: true
  # END Настройки пушей (FCM)